config/routes.rb
Rails.application.routes.draw do

  root 'static_pages#home'
  get '/contact', to: 'static_pages#contact'
  get '/signup', to: 'users#new'
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'

  resources :users do
    member do
      get :following, :followers
    end
  end
  resources :taskmemos
  resources :taskmemos, only: [:create, :destroy]
  resources :account_activations, only: [:edit]
  resources :password_resets, only: [:new, :create, :edit, :update]
  resources :relationships, only: [:create, :destroy]

  get 'print', to: 'work_process#print'
  get '/drylaminate', to: 'work_process#drylaminate'
  get '/exlaminate', to: 'work_process#exlaminate'
  get '/slit', to: 'work_process#slit'
  get '/bagmake', to: 'work_process#bagmake'

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
    if logged_in?
      @taskmemo = current_user.taskmemos.build
      @feed_items = current_user.feed.paginate(page: params[:page])
    end
  end

  def help
  end

  def about
  end

  def contact
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/static_pages/_about.html.erb
<div class="container">
  <div class="row">
    <div class="col-12 col-sm-12 col-lg-12">

    <h1>タスクをメモしよう</h1>

    <p>どこでも、どのスマホでも、どのパソコンでも
    <br>タスクを書き出せます。
    <br>タスクを整理して頭の中を整理しよう</p>

    <h2>こんな方にオススメです</h2>
    <ul>
      <li>タスクに納期が存在する</li>
      <li>タスクの打合せが多い方</li>
      <li>タスクの数が多く管理するのが面倒な方</li>
      <li>手書きでメモするのが苦手、面倒な方</li>
    </ul>

    <h3>こんなシュチュエーション<br>でも・・・</h3>
    <ul>
      <li>同じ部署野中での会議中</li>
      <li>他部署の人との打合せ中</li>
      <li>取引先との商談中</li>
      <li>協力会社との納期交渉中</li>
    </ul>

    <p><span>「そういえばさー、あれってどうなってる？」</span>と、<br>
        タスクの進捗を唐突に聞かれませんか。</p>

    <p>1つでもあてはまる方は、まずはタスクを登録して、
    <br>納期を管理してみよう！</p>
    </div>
  </div>
</div>

app/views/static_pages/_user_logged_in.html.erb
<div class="row">
  <aside class="col-md-4">
    <section class="user_info">
      <%= render 'shared/user_info' %>
    </section>
    <section class= "stats">
      <%= render 'shared/stats' %>
    </section>
    <section class="taskmemo_form">
      <%= render 'shared/taskmemo_form' %>
    </section>
  </aside>
  <div class="col-md-8">
    <h3>製品一覧</h3>
    <%= render 'shared/feed' %>
  </div>
</div>

app/views/static_pages/_user_not_logged_in.html.erb
<div class="row">
<div class="mx-auto">
<h1>Task memoで<br>納期の進捗を管理しよう</h1>
</div>
<p>さぁ始めよう！</p>
<li><%= link_to "サインアップ", signup_path, class: "btn btn-primary" %></li>
<p>ログインはこちら！</p>
<li><%= link_to "ログイン", login_path, class: "btn btn-primary" %></li>
<%= image_pack_tag 'pexels-suzy-hazelwood-1226398.jpg' %>
<%= render 'static_pages/about' %>
<div class="container">
    <div class="row">
        <div class="col-12 col-sm-12 col-lg-12">
        <p>さぁ始めよう！</p>
        <li><%= link_to "サインアップ", signup_path, class: "btn btn-primary" %></li>
        <p>ログインはこちら！</p>
        <li><%= link_to "ログイン", login_path, class: "btn btn-primary" %></li>
    </div>
</div>

app/views/static_pages/contact.html.erb
<% provide(:title, "contact") %>
<h1>StaticPages#contact</h1>
<p>Find me in app/views/static_pages/contact.html.erb</p>

app/views/static_pages/help.html.erb
<% provide(:title, "help") %>
<h1>StaticPages#help</h1>
<p>Find me in app/views/static_pages/help.html.erb</p>

app/views/static_pages/home.html.erb
<% if logged_in? %>
  <%= render 'static_pages/user_logged_in' %>
<% else %>
  <%= render 'static_pages/user_not_logged_in' %>
<% end %>