config/routes.rb
Rails.application.routes.draw do

  root 'static_pages#home'
  get '/contact', to: 'static_pages#contact'
  get '/signup', to: 'users#new'
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'

  resources :users do
    member do
      get :following, :followers
    end
  end
  resources :taskmemos
  resources :taskmemos, only: [:create, :destroy]
  resources :account_activations, only: [:edit]
  resources :password_resets, only: [:new, :create, :edit, :update]
  resources :relationships, only: [:create, :destroy]

  get 'print', to: 'work_process#print'
  get '/drylaminate', to: 'work_process#drylaminate'
  get '/exlaminate', to: 'work_process#exlaminate'
  get '/slit', to: 'work_process#slit'
  get '/bagmake', to: 'work_process#bagmake'

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/taskmemo.rb
class Taskmemo < ApplicationRecord
  belongs_to :user
  has_one_attached :image
  default_scope -> { order(created_at: :desc) }
  validates :user_id, presence: true
  validates :product_name, presence: true, length: { maximum: 30 }
  validates :order_number, presence: true, length: { maximum: 6 }
  # validates :delivery_date, presence: true
  # validates :quantity, presence: true
  validates :remarks, presence: true, length: { maximum: 140 }
  validates :image, content_type: { in: %w[image/jpeg image/gif image/png],
                                    massage: "有効な画像形式である必要があります" },
                    size: { less_than: 5.megabytes,
                            message: "5MB未満である必要があります" }

  # 表示用のリサイズ済み画像を返す
  def display_image
    image.variant(resize_to_limit: [500, 500])
  end
end

app/controllers/taskmemos_controller.rb
class TaskmemosController < ApplicationController
  before_action :logged_in_user, only: [:create, :destroy]
  before_action :correct_user, only: :destroy

  def index
    @taskmemos = current_user.taskmemos
  end

  def show
    @taskmemo = current_user.taskmemos.find(params[:id])
  end

  def new
    @taskmemo = Taskmemo.new
  end

  def create
    @taskmemo = current_user.taskmemos.build(taskmemo_params)
    @taskmemo.image.attach(params[:taskmemo][:image])
    if @taskmemo.save
      flash[:success] = "「#{@taskmemo.product_name}」を登録しました。"
      redirect_to root_url
    else
      @feed_items = current_user.feed.pagenate(page: params[:page])
      render 'static_pages/home'
    end
  end

  def edit
    @taskmemo = current_user.taskmemos.find(params[:id])
  end

  def update
    taskmemo = Taskmemo.find(params[:id])
    taskmemo.update!(taskmemo_params)
    flash[:success] = "「#{@taskmemo}」を編集しました。"
    redirect_to root_url
  end

  def destroy
    @taskmemo.destroy
    flash[:success] = "製品を削除しました。"
    redirect_back(fallback_location: root_url)
  end

  private

  def taskmemo_params
    params.require(:taskmemo).permit(:product_name, :order_number,
                                    :delivery_date, :quantity,
                                    :process, :remarks, :image)
  end

  def correct_user
    @taskmemo = current_user.taskmemos.find_by(id: params[:id])
    redirect_to root_url if @taskmemo.nil?
  end
end

app/views/taskmemos/_form.html.erb
<%= form_with(model: @taskmemo, local: true) do |f| %>
  <%= render 'shared/error_messages', object: f.object %>

  <%= f.label :product_name, "製品名" %>
  <%= f.text_field :product_name, class: 'form-control' %>

  <%= f.label :order_number, "注番" %>
  <%= f.text_field :order_number, :placeholder => "B20001",
                                  class: 'form-control' %>

  <%= f.label :created_at, "製造日", class: 'control-label' %>
  <%= f.date_field :created_at, class: 'form-control' %>

  <%= f.label :delivery_date, "納期", class: 'control-label' %>
  <%= f.date_field :created_at, class: 'form-control' %>

  <%= f.label :quantity, "手配数量" %>
  <%= f.text_field :quantity, :placeholder => "2000m・4000m・8000m・12000m",
                              class: 'form-control' %>
  <div class= "form-group">
    <%= f.label :process, "工程", class: 'control-label' %>
    <%= f.select :process, ["印刷・ラミネート・スリット", "印刷・スリット",
                            "印刷・ラミネート・製袋",
                            "印刷・ラミネート・スリット・製袋"],
                            include_blank: "選択してください",
                            class: 'form-control', required: true %>
  </div>

  <%= f.label :remarks, "備考" %>
  <%= f.text_field :remarks, class: 'form-control' %>

  <%= f.submit yield(:button_text), class: "btn btn-primary" %>
<% end %>

app/views/taskmemos/_taskmemo.html.erb
<li id="taskmemo-<%= taskmemo.id %>">
  <span>ID<%= taskmemo.id %></span>
  <span class="order_number">注番<%= taskmemo.order_number %></span>
  <span class="product_name">品名<%= link_to taskmemo.product_name,
                                                      taskmemo_path(taskmemo) %>
  </span>
</li>
<li>
  <span class="created_at">製造日<%= taskmemo.created_at.strftime('%Y/%m/%d') %></span>
  <span class="delivery_date">納期<%= taskmemo.delivery_date %></span>
  <span class="quantity">数量<%= taskmemo.quantity %></span><br>
  <span class="process">工程<%= taskmemo.process %></span>
</li>
<li>
  <span class="remarks">備考<%= taskmemo.remarks %></span>
</li>
<li>
  <span class="image">画像
  <%= image_tag taskmemo.display_image if taskmemo.image.attached? %></span>
</li>
<li>
  <span class="timestamp">
  投稿 <%= time_ago_in_words(taskmemo.created_at) %> 前。
  </span>
  <% if current_user?(taskmemo.user) %>
    <%= link_to "編集", edit_taskmemo_path(taskmemo), class: "btn btn-primary mr-3" %>
    <%= link_to "削除", taskmemo, method: :delete,
                                  data: { confirm: "「#{taskmemo.product_name}」を削除します。よろしいですか？" },
                                  class: 'btn btn-danger' %>
  <% end %>
</li>

app/views/taskmemos/edit.html.erb
<% provide(:title, 'Product edit') %>
<% provide(:button_text, '製品登録') %>
<h1>製品編集</h1>
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= render 'form' %>
  </div>
</div>

app/views/taskmemos/index.html.erb
<% provide(:title, 'All tasks') %>
<h1>All items</h1>

<ul class="nav nav-tabs" id="myTab" role="tablist">
  <li class="nav-item nav-link actice" id="home-tab" data-toggle="tab" href="#nav-home" role="tab" aria-controls="home" aria-selected="true">
  <%= link_to "印刷", print_path %>
  </li>
  <li class="nav-item nav-link actice" id="home-tab" data-toggle="tab" href="#nav-home" role="tab" aria-controls="home" aria-selected="true">
  <%= link_to "ドライラミネート", drylaminate_path %>
  </li>
  <li class="nav-item nav-link actice" id="home-tab" data-toggle="tab" href="#nav-home" role="tab" aria-controls="home" aria-selected="true">
  <%= link_to "押出しラミネート", exlaminate_path %>
  </li>
  <li class="nav-item nav-link actice" id="home-tab" data-toggle="tab" href="#nav-home" role="tab" aria-controls="home" aria-selected="true">
  <%= link_to "スリット", slit_path %>
  </li>
  <li class="nav-item nav-link actice" id="home-tab" data-toggle="tab" href="#nav-home" role="tab" aria-controls="home" aria-selected="true">
  <%= link_to "製袋", bagmake_path %>
  </li>
</ul>

app/views/taskmemos/new.html.erb
<% provide(:title, 'Product entry') %>
<% provide(:button_text, '製品登録') %>
<h1>製品登録</h1>
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= render 'form' %>
  </div>
</div>

app/views/taskmemos/show.html.erb
<% provide(:title, @taskmemo.product_name) %>
<nav class="row justify-content-end">
  <div class="col-md-4">
    <table class= "table table table-hover">
      <tbody>
        <tr><th>ID</th><td><%= @taskmemo.id %></td></tr>
        <tr><th>品名</th><td><%= @taskmemo.product_name %></td></tr>
        <tr><th>注番</th><td><%= @taskmemo.order_number %></td></tr>
        <tr><th>製造日</th><td><%= @taskmemo.created_at %></td></tr>
        <tr><th>納期</th><td><%= @taskmemo.delivery_date %></td></tr>
        <tr><th>手配数量</th><td><%= @taskmemo.quantity %></td></tr>
        <tr><th>作業工程</th><td><%= @taskmemo.process %></td></tr>
        <tr><th>備考</th><td><%= @taskmemo.remarks %></td></tr>
        <tr><th>更新日時</th><td><%= @taskmemo.updated_at %></tr>
        <td><%= link_to "編集", edit_taskmemo_path, class: "btn btn-primary" %></td>
        <td><%= link_to "削除", @taskmemo, method: :delete,
                            data: { confirm: "「#{@taskmemo.product_name}」を削除します。よろしいですか？" },
                            class: 'btn btn-danger' %></td>
      </tbody>
    </table>
  </div>
</nav>