config/routes.rb
Rails.application.routes.draw do

  root 'static_pages#home'
  get '/contact', to: 'static_pages#contact'
  get '/signup', to: 'users#new'
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'

  resources :users do
    member do
      get :following, :followers
    end
  end
  resources :taskmemos
  resources :taskmemos, only: [:create, :destroy]
  resources :account_activations, only: [:edit]
  resources :password_resets, only: [:new, :create, :edit, :update]
  resources :relationships, only: [:create, :destroy]

  get 'print', to: 'work_process#print'
  get '/drylaminate', to: 'work_process#drylaminate'
  get '/exlaminate', to: 'work_process#exlaminate'
  get '/slit', to: 'work_process#slit'
  get '/bagmake', to: 'work_process#bagmake'

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      このフォームには <%= pluralize(object.errors.count, "エラー") %>.
    </div>
    <ul>
    <% object.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_feed.html.erb
<% if @feed_items.any? %>
  <ol class="taskmemos">
    <%= render @feed_items %>
  </ol>
  <%= will_paginate @feed_items,
                    params: { controller: :static_pages, action: :home } %>
<% end %>

app/views/shared/_stats.html.erb
<% @user ||= current_user %>
<div class="stats">
  <a href="<%= following_user_path(@user) %>">
    <strong id="following" class="stat">
      <%= @user.following.count %>
    </strong>
    following
  </a>
  <a href="<%= followers_user_path(@user) %>">
    <strong id="followers" class="stat">
      <%= @user.followers.count %>
    </strong>
    フォロワー
  </a>
</div>

app/views/shared/_taskmemo_form.html.erb
<% provide(:button_text, '製品登録') %>
<h1>製品登録へ</h1>
<%= form_with(model: @taskmemo, local: true) do |f| %>
  <%= render 'shared/error_messages', object: f.object %>

  <%= f.label :order_number, "注番" %>
  <%= f.text_field :order_number, :placeholder => "B20001",
                                   class: 'form-control' %>

  <%= f.label :product_name, "製品名" %>
  <%= f.text_field :product_name, class: 'form-control' %>

  <%= f.label :created_at, "製造日", class: 'control-label' %>
  <%= f.date_field :created_at, class: 'form-control' %>

  <%= f.label :delivery_date, "納期", class: 'control-label' %>
  <%= f.date_field :created_at, class: 'form-control' %>

  <%= f.label :quantity, "手配数量" %>
  <%= f.text_field :quantity, :placeholder => "2000m・4000m・8000m・12000m",
                              class: 'form-control' %>
  <div class= "form-group">
    <%= f.label :process, "工程", class: 'control-label' %>
    <%= f.select :process, ["印刷・ラミネート・スリット", "印刷・スリット",
                          "印刷・ラミネート・製袋",
                          "印刷・ラミネート・スリット・製袋"],
                          include_blank: "選択してください",
                          class: 'form-control', required: true %>
  </div>

  <%= f.label :remarks, "備考" %>
  <%= f.text_field :remarks, class: 'form-control' %>

  <span class= "image">
    <%= f.file_field :image, accept: "image/jpeg,image/gif,image/png" %>
  </span>
  <%= f.submit yield(:button_text), class: "btn btn-primary" %>
<% end %>

<script type="text/javascript">
  $("#taskmemo_image").bind("change", function() {
    var size_in_megabytes = this.files[0].size/1024/1024;
    if (size_in_megabytes > 5) {
      alert("最大ファイルサイズは5MBです。 小さいファイルを選択してください。");
      $("#micropost_image").val("");
    }
  });
</script>

app/views/shared/_user_info.html.erb
<%= link_to gravatar_for(current_user, size: 50), current_user %>
<h1><%= current_user.name %></h1>
<span><%= link_to "プロフィールを見る", current_user %></span>
<span><%= pluralize(current_user.taskmemos.count, "登録製品") %></span>