config/routes.rb
Rails.application.routes.draw do

  root 'static_pages#home'
  get '/contact', to: 'static_pages#contact'
  get '/signup', to: 'users#new'
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'

  resources :users do
    member do
      get :following, :followers
    end
  end
  resources :taskmemos
  resources :taskmemos, only: [:create, :destroy]
  resources :account_activations, only: [:edit]
  resources :password_resets, only: [:new, :create, :edit, :update]
  resources :relationships, only: [:create, :destroy]

  get 'print', to: 'work_process#print'
  get '/drylaminate', to: 'work_process#drylaminate'
  get '/exlaminate', to: 'work_process#exlaminate'
  get '/slit', to: 'work_process#slit'
  get '/bagmake', to: 'work_process#bagmake'

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    Web app made by <a href="#">kosuke furuta</a>
  </small>
  <div class="center">
    <ul>
      <li><%= link_to "問い合わせ", contact_path %></li>
      <li><a href="#">自己紹介</a></li>
      <li><a href="https://github.com/kosuke-furuta/memo">githubコード</a></li>
    </ul>
  </div>
</footer>

app/views/layouts/_head.html.erb
<head>
  <title><%= full_title(yield(:title)) %></title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <%= stylesheet_pack_tag 'application', media: 'all',
                          'data-turbolinks-track': 'reload' %>
  <%= javascript_pack_tag 'application',
                          'data-turbolinks-track': 'reload' %>
</head>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top">
<div class="container">
  <div class="row">
    <%= link_to "Task Memo", root_path, id: "logo" %>
  </div>
  <div class="row">
    <div class="visible-xs-block">
      <ul class="nav navbar-white bg-white">
        <li><%= link_to "ホーム", root_path %></li>
        <% if logged_in? %>
          <% if current_user.admin? %>
            <li><%= link_to "ユーザー", users_path %></li>
          <% end %>
          <li><%= link_to "タスク", taskmemos_path %></li>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              アカウント <b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
              <li><%= link_to "プロフィール", current_user %></li>
              <li><%= link_to "プロフィール編集", edit_user_path(current_user) %></li>
              <li class="divider"></li>
              <li>
                <%= link_to "ログアウト", logout_path, method: :delete %>
              </li>
            </ul>
          </li>
        <% else %>
          <li><%= link_to "ログイン", login_path %></li>
        <% end %>
      </ul>
    </div>
  </div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>  
<html lang="ja">
  <%= render 'layouts/head' %>
  <%= render 'layouts/shim' %>
  <body>
    <%= render 'layouts/header' %>
    <div class= "container">
      <% flash.each do |message_type, message| %>
        <%= content_tag(:div, message, class: "alert alert-#{message_type}") %>
      <% end %>
      <%= yield %>
      <%= render 'layouts/footer' %>
      <%= debug(params) if Rails.env.development? %>
    </div>
  </body>
</html>